// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7xwga2zgBt8GxVadzetyIy22gLXNnUKA',
    appId: '1:712823650359:web:75e422fda5562aa149a7b2',
    messagingSenderId: '712823650359',
    projectId: 'flutter-app-d7ef2',
    authDomain: 'flutter-app-d7ef2.firebaseapp.com',
    storageBucket: 'flutter-app-d7ef2.appspot.com',
    measurementId: 'G-5FCY7GDVZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmRBePkQE-T4JJH6h0_WNX5TuvtV87apE',
    appId: '1:712823650359:android:43a2b3e9605c763449a7b2',
    messagingSenderId: '712823650359',
    projectId: 'flutter-app-d7ef2',
    storageBucket: 'flutter-app-d7ef2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjtlmc3K74-CV-XWvT3IcUbmM57ujG54k',
    appId: '1:712823650359:ios:b3bbf7aaae5d15bc49a7b2',
    messagingSenderId: '712823650359',
    projectId: 'flutter-app-d7ef2',
    storageBucket: 'flutter-app-d7ef2.appspot.com',
    iosClientId: '712823650359-360qspmrdn6g6q8lbcr4q8e61qg4702i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjtlmc3K74-CV-XWvT3IcUbmM57ujG54k',
    appId: '1:712823650359:ios:b3bbf7aaae5d15bc49a7b2',
    messagingSenderId: '712823650359',
    projectId: 'flutter-app-d7ef2',
    storageBucket: 'flutter-app-d7ef2.appspot.com',
    iosClientId: '712823650359-360qspmrdn6g6q8lbcr4q8e61qg4702i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
